---
title: "R Notebook"
output: html_notebook
---

Michael Hornsby Exercise Set 8

libraries

```{r include=FALSE}
library(here)
library(tidyverse)
library(ggrepel)
library(scales)
library(readxl)
```


Number 1

Create function

```{r}
my.function <- function(dataset, numeric, reverse) {

reverse <- reverse + 1
numeric <- numeric + 1
reverse_dataset <- dataset

for (i in reverse) {
  reverse_dataset[i] <- abs(reverse_dataset[i] - numeric)
}

dataset$total <- rowSums(reverse_dataset[,2:as.numeric(ncol(reverse_dataset))])

print(dataset)

}
```



Number 2

read in the data and send to function

```{r}
hypothetical <- read_csv(here("data", "hypothetical.csv"))

my.function(hypothetical, 6, c(2,3,8))
```



Number 3

```{r}
hsb2 <- read_excel(here("data", "hsb2.xlsx"))

hsb2$gender <- factor(hsb2$female, labels = c("male", "female"))

ggplot(data = hsb2) + 
  geom_point(mapping = aes(x = math, y = science, color = gender))
```



Number 4

```{r}
ggplot(data = hsb2) + 
  geom_point(mapping = aes(x = math, y = science)) +
  facet_wrap(~gender)
```


Number 5
```{r}
ggplot(data = hsb2) + 
  geom_qq(aes(sample=math))

# This is a qq-plot of the math scores in the hsb2 dataset.  This will give
# us a sense of whether or not we have a normally distributed math variable.
```

